### PR TITLE
Updated latest istat cities file

### PR DESCRIPTION
**Pull request by KrisXVII**
I updated the latest cities file from the istat, the file encoding is UTF-8 so it shouldn't cause any problem and the .idea is untouched. Let me know if everything is alright for the merge of the changes.

### CODE REVIEW

**Comment by KrisXVII** [comment]
Hey, um.. could you let me know if everything is alright with that commit?

**Comment by KrisXVII** [comment]
Sorry to bother you but I would need that merge, is it all good with that commit?

**Comment by topac** [comment]
Hi there, I'm sorry but I'm going to check this on late December since I
have no time now.

**Comment by KrisXVII** [comment]
Hey, it's been a while. Have you got any time now to perform a little check and allow the merge if it's all good?

**Comment by KrisXVII** [comment]
Hey, um,  it's been 2 months and I still need that feature, give it a look and tell me it everything is fine, please. It takes less than
 2 minutes to check it's not big deal.

**Comment by topac** [comment]
Hey I'm back.
I was looking at the changes and they fall into 2 categories:
1. A town changed it's name. For e.g. "Calliano" it is now called "Calliano Monferrato" keeping the same code B418.
2. A town is no more a town! E.g. "Brez" since the [1st January of 2020 has been absorbed by its bigger neighbor](https://it.wikipedia.org/wiki/Brez).  

I see no issues with case no. 1 but case no. 2 it's tricky. 
If we remove the line from the .csv, someone born in Brez trying to use a website that rely on this gem to calculate its fiscal code will receive an error. We should add a new column to the .csv, something like "defunct" (true, false) or "defunctAt" (date) in order to allow old fiscal codes to work and maybe raise an error if someone what to calculate a fiscal code using Brez as town an a date > 2020/01/01.

What do you think?

**Comment by KrisXVII** [comment]
Well, it's just about some fixing in the website, like, the one I'm developing throws an error saying that the city is not available if trying to calculate the fiscal code. If someone tried to calculate the code through this gem and the system has already implemented an error management it wouldn't be a problem in my opinion.
Has the file ever been updated before? Maybe we could draw on last update do understand what it's better to do, but to me point #2 doesn't seem to be a huge problem. Let me know if my point is clear and if you agree.

**Comment by KrisXVII** [comment]
Or we could leave there the cities that now no longer exist so that the gem can work also for the ones that were there before.

**Comment by Obasoro** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[Celestia Banner](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!geoffreysteven, @kuafou, @ptspzy, @krakxn, @confidentmeerkat, @Bertha7179, @flada-auxv, @adityavyas, @mmsaki, @atilaahmettaner, @miyao-gmo, @iam-medvedev, @dCipher-io, @fantasybei, @mustafacanp, @xana-rahmani, @m1noon, @FLAKEYCHALK, @TheStarBoys, @laolin

**Comment by KrisXVII** [comment]
Hey, um, you got any news? Can we finish this?

**Comment by KrisXVII** [comment]
Maaaaan this has been going on since October, can we please end this?

**Comment by topac** [comment]
Hi there sorry, can you just add new cities (or rename the cities that changed name in the past year) but leave the removed ones?

**Comment by KrisXVII** [comment]
Yes, I'm going to do this as soon as I have some time, I'll notify you when it's done👍🏼Inviato da iPhoneIl giorno 25 mar 2024, alle ore 21:09, d ***@***.***> ha scritto:﻿
Hi there sorry, can you just add new cities (or rename the cities that changed name in the past year) but leave the removed ones?

**Pull request closed without merging**
